# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eb971d37c1549c60a537c5e7040ab1ece71b82cc5dd8cf7746070f2c68a9b83bcb36810eae05f2692f68c97eda1c67072c5998b2e4d33351ce410ab469dd6266

test:
  secret_key_base: 637fba0a6b0aafa8c5bd993d4c6c448ed2574db43ee4e3532a2e4836cbd9b3a8aa6065aea6a8854a70b63870a278fb1ea5a429029e043d016621056d1b2355ec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
